#!/bin/bash

task_name=$1

if [ -z "$task_name" ]; then
  echo "Usage: cpinit [task_name]"
  exit 1
fi

if [ -z "$CP_UTILS" ]; then
  echo "Error: CP_UTILS environment variable is not set."
  exit 1
fi

# Define the source template directory
template_dir="$CP_UTILS/template"

# Check if the template directory exists
if [ ! -d "$template_dir" ]; then
  echo "Error: Template directory '$template_dir' does not exist."
  exit 1
fi

cp -r "$template_dir" "$task_name"
exit 0
