title: Team xVenom CP
description: Competitive programming resources
baseurl: "/cp" # the subpath of your site, e.g. /blog
  # Change this to "" for local render
url: "https://terxor.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: terxor

remote_theme: pmarsceill/just-the-docs

aux_links:
  "View on GitHub":
    - "//github.com/terxor/cp"

compress_html:
  blanklines: true

markdown: kramdown
kramdown:
  math-engine: katex
  input: GFM
  syntax_highlighter: rouge

plugins:
    - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
